version: '2'
services:
  openvpn:
    cap_add:
    - NET_ADMIN
    image: awalach/openvpn
    container_name: openvpn
    ports:
    - "1194:1194/udp"
    restart: always
    depends_on:
    - "gui"
    volumes:
    - ./openvpn-data/conf:/etc/openvpn
  gui:
    image: intrigues/openvpn-web-ui:0.1
    container_name: openvpn-gui
    environment:
    - OPENVPN_ADMIN_USERNAME=admin
    - OPENVPN_ADMIN_PASSWORD=b3secure
    - COUNTRY=IN
    - PROVINCE=GJ
    - CITY=ADI
    - ORG=INTRIGUES
    - EMAIL=intrigues@gmail.com
    - OU=IT
    ports:
    - "8080:8080/tcp"
    restart: always
    volumes:
    - ./openvpn-data/conf:/etc/openvpn
    - ./openvpn-data/db:/opt/openvpn-gui/db
